{% set name = "pathlib-abc" %}
{% set version = "0.3.0" %}
{% set pypi_name = name.replace("-", "_") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: 87a25bde89d29f48d04e2dcff7a12d9ffe93096fe775b4ad3fd34814c0d3a814

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
  run:
    - python >=3.8

test:
  imports:
    - pathlib_abc

about:
  home: https://github.com/barneygale/pathlib-abc
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE
  summary: Base classes for pathlib.Path-ish objects
  dev_url: https://github.com/barneygale/pathlib-abc

extra:
  recipe-maintainers:
    - kfot
