{% set name = "pathlib-abc" %}
{% set version = "0.2.0" %}
{% set pypi_name = name.replace("-", "_") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: b9af6b39fd51321485678ec3803d0a11e02a22e869e8052cacb6e8f65de7b862

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
  run:
    - python >=3.8

test:
  imports:
    - pathlib_abc

about:
  home: https://github.com/barneygale/pathlib-abc
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE
  summary: Base classes for pathlib.Path-ish objects
  dev_url: https://github.com/barneygale/pathlib-abc

extra:
  recipe-maintainers:
    - kfot
